version: '3.9'
services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: earthquakes
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: earthquakes
    volumes:
      - .:/app
